
version: "3.8"

services:
  mysqldb:
    container_name: container
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      springboot-mysql-net:
    volumes:
      - task:/var/lib/mysql

  taskmanager:
    container_name: task_manager
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: on-failure

networks:
  springboot-mysql-net:
volumes:
  task: